### Class exercise: table
![](../../images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [8]:
import numpy as np
a = np.arange(10, 30).reshape(4,5)
red = a[0, 1:4]
blue   = a[::2, 4]  
green  = a[0:3, 2] 
tegl = a[:, 1::2] 
yellow = a[0, 0] 
print('red:',red,'\nblue:',blue,'\ngreen:\n',green,'\ntegl:',tegl, '\nyellow:',yellow)


red: [11 12 13] 
blue: [14 24] 
green:
 [12 17 22] 
tegl: [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
yellow: 10


### 3D
reshape can be done with multiple dimensions. Here is an example with 3d  
`a = np.arange(0, 27).reshape((3, 3, 3))`  
![](../../images/cube.png)
### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.


In [10]:
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
ex1 = a[1,1,:]
ex2 = a[:,1,0]
ex3 = a[0,:,2]
print(ex1)
print("-----------------------")
print(ex2)
print("-----------------------")
print(ex3)
print("-----------------------")
print(a)

[12 13 14]
-----------------------
[ 3 12 21]
-----------------------
[2 5 8]
-----------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6
  - using the operators: `%` and `|` mask to only get numbers that are divisible by 3 and numbers begining with 8

In [92]:
data = np.arange(1,101).reshape(10,10)
a = data[data % 2 == 0]
b = np.where(data % 10 == 6, data, 0)
c = np.where((data >= 80) & (data < 90) | (data % 3 == 0) | (data == 8), data, 0)
print(a)
print("-------------------------------")
print(b)
print("-------------------------------")
print(c)
print("-------------------------------")

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
-------------------------------
[[ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0 16  0  0  0  0]
 [ 0  0  0  0  0 26  0  0  0  0]
 [ 0  0  0  0  0 36  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  0]
 [ 0  0  0  0  0 56  0  0  0  0]
 [ 0  0  0  0  0 66  0  0  0  0]
 [ 0  0  0  0  0 76  0  0  0  0]
 [ 0  0  0  0  0 86  0  0  0  0]
 [ 0  0  0  0  0 96  0  0  0  0]]
-------------------------------
[[ 0  0  3  0  0  6  0  8  9  0]
 [ 0 12  0  0 15  0  0 18  0  0]
 [21  0  0 24  0  0 27  0  0 30]
 [ 0  0 33  0  0 36  0  0 39  0]
 [ 0 42  0  0 45  0  0 48  0  0]
 [51  0  0 54  0  0 57  0  0 60]
 [ 0  0 63  0  0 66  0  0 69  0]
 [ 0 72  0  0 75  0  0 78  0 80]
 [81 82 83 84 85 86 87 88 89 90]
 [ 0  0 93  0  0 96  0  0 99  0]]
-------------------------------
